### ISSUE TITLE
Sintesis.Julissa Migdalia Jose Cruz

### ISSUE THREAD

**Issue by Julissamigdalia** [SistemasTecTlaxiaco/actividad-3-sintesis-Julissamigdalia#2]
[SINTESIS.JULISSA MIGDALIA JOSE CRUZ.pdf](https://github.com/user-attachments/files/16840841/SINTESIS.JULISSA.MIGDALIA.JOSE.CRUZ.pdf)

**Comment by Elisahadad** [comment]
Calificación = 20

**Comment by josealfredo79** [comment]
Falta la bibliografia...la calificacion es de 18 por favor..
